# Generated by Django 5.2.7 on 2025-10-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_full_refresh_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField()),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('estimated_gdp', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
