# Generated by Django 5.2.7 on 2025-10-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachestatus',
            name='last_full_refresh_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
